### ISSUE TITLE
There was no fonts in Linux version

### ISSUE THREAD

**Issue by JamesMung** [AdoptOpenJDK/openjdk8-releases#16]
JDK Version ; jdk8u181-b13

When I use jasper print PDF in Windows is fine, but for Linux found the error as follow:
```java
Caused by: net.sf.jasperreports.engine.JRRuntimeException: java.io.IOException: Problem reading font data.
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.<init>(SimpleFontFace.java:108)
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.<init>(SimpleFontFace.java:128)
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.getInstance(SimpleFontFace.java:67)
        at net.sf.jasperreports.engine.fonts.SimpleFontFamily.setNormal(SimpleFontFamily.java:99)
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.parseFontFamily(SimpleFontExtensionHelper.java:261)
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.parseFontFamilies(SimpleFontExtensionHelper.java:232)
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.loadFontFamilies(SimpleFontExtensionHelper.java:193)
        at net.sf.jasperreports.engine.fonts.SimpleFontExtensionHelper.loadFontFamilies(SimpleFontExtensionHelper.java:162)
        at net.sf.jasperreports.engine.fonts.FontExtensionsRegistry.getExtensions(FontExtensionsRegistry.java:56)
        at net.sf.jasperreports.extensions.DefaultExtensionsRegistry.getExtensions(DefaultExtensionsRegistry.java:110)
        at net.sf.jasperreports.engine.util.JRStyledTextParser.<clinit>(JRStyledTextParser.java:83)
        ... 73 more
Caused by: java.io.IOException: Problem reading font data.
        at java.awt.Font.createFont0(Font.java:1000)
        at java.awt.Font.createFont(Font.java:877)
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.<init>(SimpleFontFace.java:100)
        ... 83 more
```

Can you help for solve this problem in current version ? And please fix it in future version.

**Comment by karianna** [comment]
This issue was moved to AdoptOpenJDK/openjdk-build#682

**Comment by xinyi9** [comment]
Hey @karianna our team has hit this problem in adoptopenjdk8 too, I wonder if there is any reason not keeping this issue under openjdk8-releases?

**Comment by smlambert** [comment]
I believe this issue was moved to the openjdk-build repo, because the changes required to fix this 'no fonts' problem need to be done in that repo.  This issue was subsequently closed to avoid duplication as only 1 issue (https://github.com/AdoptOpenJDK/openjdk-build/issues/682) is required to track it.

**Comment by xinyi9** [comment]
Thanks @smlambert , I will keep track of that issue. :)

**Comment by cuixue** [comment]
> Thanks @smlambert , I will keep track of that issue. :)

hi, i also have met, have you solved this problem.

**Comment by karianna** [comment]
> > Thanks @smlambert , I will keep track of that issue. :)
> 
> hi, i also have met, have you solved this problem.

See the AdoptOpenJDK/openjdk-build#682 link - so not yet.
